name: LPRankUp
version: 0.0.1
author: ZeTioZ
main: fr.zetioz.lprankup.LPRankupMain
api-version: 1.16
depend: [Vault]
commands:
  lprankup:
    aliases: [lpr, rankup]
    description: Main LPRankup command