name: Conditional-GUI
version: 0.0.2
author: ZeTioZ
main: fr.zetioz.conditionalgui.ConditionalGUIMain
api-version: 1.16
depend: [Vault]
commands:
  conditionnalgui:
    aliases: [cg, cdg]
    description: Main Conditional GUI command