name: Conditional-GUI
version: 0.4.1
author: ZeTioZ
main: fr.zetioz.conditionalgui.ConditionalGUIMain
api-version: 1.16
softdepend: [mcMMO, Vault, SuperiorSkyblock]
commands:
  conditionalgui:
    aliases: [cg, cdg, rankup, rkup]
    description: Main Conditional GUI command